FROM node:18.17.0-alpine3.17

RUN apk add build-base git krb5-dev libgit2-dev libssh-dev pkgconfig python3 tzdata

ADD . /app
WORKDIR /app

RUN npm ci --ignore-scripts && \
  npm run preinstall && \
  npx prebuildify --napi --strip --tag-libc -t "$(node --version | tr -d 'v')"
